version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: repair_postgres
    environment:
      POSTGRES_DB: repair_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - repair_network

  minio:
    image: minio/minio:latest
    container_name: repair_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - repair_network

  redis:
    image: redis:7-alpine
    container_name: repair_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - repair_network

volumes:
  postgres_data:
  minio_data:
  redis_data:

networks:
  repair_network:
    driver: bridge





